/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.rivaldy.WindowApp;

import id.co.rivaldy.WindowApp.DAO.DeliveryServiceList;
import id.co.rivaldy.WindowApp.DAO.PaymentCost;
import id.co.rivaldy.WindowApp.Model.Delivery;
import id.co.rivaldy.WindowApp.Model.Dimention;
import id.co.rivaldy.WindowApp.Model.Receiver;
import id.co.rivaldy.WindowApp.Model.Sender;
import java.util.List;

/**
 *
 * @author RomyRivaldy
 */
public class WinApp extends javax.swing.JFrame {

    List<Delivery> kotaTujuan;
    Sender sender;
    Receiver receiver;
    Delivery delivery;
    Dimention dimensi;
    PaymentCost cost;

    /**
     * Creates new form WinApp
     */
    public WinApp() {
        kotaTujuan = DeliveryServiceList.kotaList();
        initComponents();

        sender = new Sender();
        receiver = new Receiver();
        delivery = new Delivery();
        dimensi = new Dimention();
        cost = new PaymentCost();
    }

    public void setSendReset() {
        namaSendField.setText("");
        noSendField.setText("");
        provinsiSendField.setText("");
        kotaSendCombo.setSelectedIndex(0);
        kotaKirimPaketLabel.setText("");
        alamatSendArea.setText("");
        kdPosSendField.setText("");
    }

    public void setReceiverReset() {
        namaReceiveField.setText("");
        noReceiveField.setText("");
        provinsiReceiverField.setText("");
        kotaReceiveCombo.setSelectedIndex(0);
        kotaTujuanPaketLabel.setText("");
        alamatReceiveArea.setText("");
        kdPosReceiveField.setText("");
    }

    public void setPaketReset() {
        noResiPaketLabel.setText("");
        beratPaketField.setText("");
        pPaketField.setText("");
        lPaketField.setText("");
        tPaketField.setText("");
        tipeCombo.setSelectedIndex(0);
        hargabarangPaketField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asuransiGroup = new javax.swing.ButtonGroup();
        metodePGroup = new javax.swing.ButtonGroup();
        formInputScrollPane = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        namaSendLabel = new javax.swing.JLabel();
        noSendLabel = new javax.swing.JLabel();
        provinsiSendLabel = new javax.swing.JLabel();
        kotaSendLabel = new javax.swing.JLabel();
        alamatSendLabel = new javax.swing.JLabel();
        namaSendField = new javax.swing.JTextField();
        noSendField = new javax.swing.JTextField();
        kotaSendCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatSendArea = new javax.swing.JTextArea();
        kdPosSendLabel = new javax.swing.JLabel();
        kdPosSendField = new javax.swing.JTextField();
        provinsiSendField = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        namaReceiveLabel = new javax.swing.JLabel();
        noReceiveLabel = new javax.swing.JLabel();
        provinsiReceiveLabel = new javax.swing.JLabel();
        kotaReceiveLabel = new javax.swing.JLabel();
        alamatReceiveLabel = new javax.swing.JLabel();
        namaReceiveField = new javax.swing.JTextField();
        noReceiveField = new javax.swing.JTextField();
        kotaReceiveCombo = new javax.swing.JComboBox<>(kotaTujuan.toArray());
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatReceiveArea = new javax.swing.JTextArea();
        kdPosReceiveLabel = new javax.swing.JLabel();
        kdPosReceiveField = new javax.swing.JTextField();
        provinsiReceiverField = new javax.swing.JTextField();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        noPaketLabel = new javax.swing.JLabel();
        tujuanPaketLabel = new javax.swing.JLabel();
        jenisPaketLabel = new javax.swing.JLabel();
        beratPaketLabel = new javax.swing.JLabel();
        tanggalPaketLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        dimensiPaketLabel = new javax.swing.JLabel();
        pPaketField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        lPaketField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tPaketField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tipePaketLabel = new javax.swing.JLabel();
        asuransiPaketLabel = new javax.swing.JLabel();
        hargaPaketLabel = new javax.swing.JLabel();
        metodePaketLabel = new javax.swing.JLabel();
        noResiPaketLabel = new javax.swing.JLabel();
        kotaTujuanPaketLabel = new javax.swing.JLabel();
        beratPaketField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tanggalKirimDate = new com.toedter.calendar.JDateChooser();
        tipeCombo = new javax.swing.JComboBox<>();
        yesAsuransiRadio = new javax.swing.JRadioButton();
        noAsuransiRadio = new javax.swing.JRadioButton();
        hargabarangPaketField = new javax.swing.JTextField();
        kotaKirimPaketLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jenisCombo = new javax.swing.JComboBox<>();
        metodeCombo = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        printOutArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formInputScrollPane.setToolTipText("");
        formInputScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("APLIKASI PENGIRIMAN BARANG");

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));

        namaSendLabel.setText("Nama");

        noSendLabel.setText("No. Telp/Hp");

        provinsiSendLabel.setText("Provinsi");

        kotaSendLabel.setText("Kota");

        alamatSendLabel.setText("Alamat");

        kotaSendCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jakarta" }));
        kotaSendCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                kotaSendComboItemStateChanged(evt);
            }
        });
        kotaSendCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotaSendComboActionPerformed(evt);
            }
        });

        alamatSendArea.setColumns(20);
        alamatSendArea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        alamatSendArea.setRows(5);
        jScrollPane1.setViewportView(alamatSendArea);

        kdPosSendLabel.setText("Kode Pos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(namaSendLabel)
                        .addGap(40, 40, 40)
                        .addComponent(namaSendField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noSendLabel)
                            .addComponent(provinsiSendLabel)
                            .addComponent(kotaSendLabel)
                            .addComponent(alamatSendLabel)
                            .addComponent(kdPosSendLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noSendField)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kotaSendCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kdPosSendField))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(provinsiSendField))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaSendLabel)
                    .addComponent(namaSendField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noSendLabel)
                    .addComponent(noSendField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provinsiSendLabel)
                    .addComponent(provinsiSendField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotaSendLabel)
                    .addComponent(kotaSendCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatSendLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kdPosSendLabel)
                    .addComponent(kdPosSendField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Pengirim", jPanel2);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));

        namaReceiveLabel.setText("Nama");

        noReceiveLabel.setText("No. Telp/Hp");

        provinsiReceiveLabel.setText("Provinsi");

        kotaReceiveLabel.setText("Kota");

        alamatReceiveLabel.setText("Alamat");

        namaReceiveField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaReceiveFieldActionPerformed(evt);
            }
        });

        noReceiveField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noReceiveFieldActionPerformed(evt);
            }
        });

        alamatReceiveArea.setColumns(20);
        alamatReceiveArea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        alamatReceiveArea.setRows(5);
        jScrollPane2.setViewportView(alamatReceiveArea);

        kdPosReceiveLabel.setText("Kode Pos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noReceiveLabel)
                    .addComponent(provinsiReceiveLabel)
                    .addComponent(kotaReceiveLabel)
                    .addComponent(namaReceiveLabel)
                    .addComponent(alamatReceiveLabel)
                    .addComponent(kdPosReceiveLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(namaReceiveField)
                    .addComponent(noReceiveField)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kotaReceiveCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kdPosReceiveField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(provinsiReceiverField))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaReceiveLabel)
                    .addComponent(namaReceiveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noReceiveLabel)
                    .addComponent(noReceiveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provinsiReceiveLabel)
                    .addComponent(provinsiReceiverField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotaReceiveLabel)
                    .addComponent(kotaReceiveCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatReceiveLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kdPosReceiveLabel)
                    .addComponent(kdPosReceiveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Data Penerima", jPanel3);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));

        noPaketLabel.setText("No. Paket");

        tujuanPaketLabel.setText("Dari");

        jenisPaketLabel.setText("Jenis Barang");

        beratPaketLabel.setText("Berat Barang");

        tanggalPaketLabel.setText("Tanggal Kirim");

        dimensiPaketLabel.setText("Dimensi");

        jLabel21.setText("cm");

        jLabel20.setText("cm");

        jLabel22.setText("cm");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dimensiPaketLabel)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pPaketField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(lPaketField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(tPaketField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(dimensiPaketLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pPaketField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(lPaketField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPaketField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)))
        );

        tipePaketLabel.setText("Tipe Paket");

        asuransiPaketLabel.setText("Asuransi");

        hargaPaketLabel.setText("Harga Barang");

        metodePaketLabel.setText("Pembayaran");

        noResiPaketLabel.setText("        ");

        kotaTujuanPaketLabel.setText("      ");

        jLabel29.setText("kg");

        tanggalKirimDate.setDateFormatString("dd/MM/YYYY");

        tipeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "Kilat", "SDS", "ONS", "HDS" }));

        asuransiGroup.add(yesAsuransiRadio);
        yesAsuransiRadio.setText("Ya");
        yesAsuransiRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesAsuransiRadioActionPerformed(evt);
            }
        });

        asuransiGroup.add(noAsuransiRadio);
        noAsuransiRadio.setText("Tidak");
        noAsuransiRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noAsuransiRadioActionPerformed(evt);
            }
        });

        kotaKirimPaketLabel.setText("        ");

        jLabel3.setText("Ke");

        jenisCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dokumen", "Elektronik", "Makanan" }));

        metodeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit", "Credit Card" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipePaketLabel)
                            .addComponent(asuransiPaketLabel)
                            .addComponent(hargaPaketLabel)
                            .addComponent(metodePaketLabel))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(yesAsuransiRadio)
                                .addGap(18, 18, 18)
                                .addComponent(noAsuransiRadio))
                            .addComponent(tipeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hargabarangPaketField)
                            .addComponent(metodeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noPaketLabel)
                            .addComponent(jenisPaketLabel)
                            .addComponent(beratPaketLabel)
                            .addComponent(tanggalPaketLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tujuanPaketLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kotaKirimPaketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(noResiPaketLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(beratPaketField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel29))
                                    .addComponent(tanggalKirimDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jenisCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kotaTujuanPaketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noPaketLabel)
                    .addComponent(noResiPaketLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tujuanPaketLabel)
                    .addComponent(kotaTujuanPaketLabel)
                    .addComponent(kotaKirimPaketLabel)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisPaketLabel)
                    .addComponent(jenisCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beratPaketLabel)
                    .addComponent(beratPaketField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalPaketLabel)
                    .addComponent(tanggalKirimDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipePaketLabel)
                    .addComponent(tipeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asuransiPaketLabel)
                    .addComponent(yesAsuransiRadio)
                    .addComponent(noAsuransiRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaPaketLabel)
                    .addComponent(hargabarangPaketField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(metodePaketLabel)
                    .addComponent(metodeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Data Paket", jPanel1);

        submitButton.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        Reset.setText("Reset");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)), "Test", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria Math", 1, 14))); // NOI18N

        printOutArea.setEditable(false);
        printOutArea.setColumns(20);
        printOutArea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        printOutArea.setRows(5);
        jScrollPane3.setViewportView(printOutArea);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTabbedPane2)
                            .addComponent(jTabbedPane1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        formInputScrollPane.setViewportView(jPanel5);

        jMenu1.setText("File");

        jMenuItem2.setText("Form");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Report");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formInputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formInputScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaReceiveFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaReceiveFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaReceiveFieldActionPerformed

    private void noReceiveFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noReceiveFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noReceiveFieldActionPerformed

    private void kotaSendComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_kotaSendComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_kotaSendComboItemStateChanged

    private void kotaSendComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotaSendComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kotaSendComboActionPerformed

    private void noAsuransiRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noAsuransiRadioActionPerformed
        if (noAsuransiRadio.isSelected()) {
            hargabarangPaketField.setEnabled(true);
        }
    }//GEN-LAST:event_noAsuransiRadioActionPerformed

    private void yesAsuransiRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesAsuransiRadioActionPerformed
        if (yesAsuransiRadio.isSelected()) {
            hargabarangPaketField.setEnabled(false);
        }
    }//GEN-LAST:event_yesAsuransiRadioActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //Input Pengirim
        sender.setNamaPengirim(namaSendField.getText().trim());
        sender.setNoHp(noSendField.getText().trim());
        sender.setProvinsi(provinsiSendField.getText().trim());
        sender.setKota((String) kotaSendCombo.getSelectedItem());
        sender.setAlamat(alamatSendArea.getText().trim());
        sender.setKdPos(kdPosSendField.getText().trim());

        //Input Penerima
        receiver.setNamaPenerima(namaReceiveField.getText().trim());
        receiver.setNoHp(noReceiveField.getText().trim());
        receiver.setProvinsi(provinsiReceiverField.getText().trim());
        receiver.setKota((String) kotaReceiveCombo.getSelectedItem());
        receiver.setAlamat(alamatReceiveArea.getText().trim());
        receiver.setKdPos(kdPosReceiveField.getText().trim());

        //Input Paket
        if (yesAsuransiRadio.isSelected()) {
            delivery.setAsuransi(true);
            //Proses
            delivery.setNoPaket(noResiPaketLabel.getText());
            delivery.setJenisBarang((String) jenisCombo.getSelectedItem());
            delivery.setBeratBarang(Double.parseDouble(beratPaketField.getText()));
            delivery.setTglKirim(tanggalKirimDate.getDate());
            dimensi.setPanjang(Double.parseDouble(pPaketField.getText()));
            dimensi.setLebar(Double.parseDouble(lPaketField.getText()));
            dimensi.setTinggi(Double.parseDouble(tPaketField.getText()));
            delivery.setTipePaket((String) tipeCombo.getSelectedItem());
            delivery.setMetodePembayaran((String) metodeCombo.getSelectedItem());
            delivery.setHargaBarang(Double.parseDouble(hargabarangPaketField.getText()));

            double total = cost.hitungCost(delivery);
            
            printOutArea.setText("Pengirim \t"+sender.getNamaPengirim()+
                    "\nNo. Hp \t"+sender.getNoHp()+"\nProvinsi \t"+sender.getProvinsi()+
                    "\nKota \t"+sender.getKota()+"\nAlamat \t"+sender.getAlamat()+
                    "\nKode Pos \t"+sender.getKdPos());
            printOutArea.setText("Penerima \t"+receiver.getNamaPenerima()+
                    "\nNo. Hp \t"+receiver.getNoHp()+"\nProvinsi \t"+receiver.getProvinsi()+
                    "\nKota \t"+receiver.getKota()+"\nAlamat \t"+receiver.getAlamat()+
                    "\nKode Pos \t"+receiver.getKdPos());
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JTextArea alamatReceiveArea;
    private javax.swing.JLabel alamatReceiveLabel;
    private javax.swing.JTextArea alamatSendArea;
    private javax.swing.JLabel alamatSendLabel;
    private javax.swing.ButtonGroup asuransiGroup;
    private javax.swing.JLabel asuransiPaketLabel;
    private javax.swing.JTextField beratPaketField;
    private javax.swing.JLabel beratPaketLabel;
    private javax.swing.JLabel dimensiPaketLabel;
    private javax.swing.JScrollPane formInputScrollPane;
    private javax.swing.JLabel hargaPaketLabel;
    private javax.swing.JTextField hargabarangPaketField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JComboBox<String> jenisCombo;
    private javax.swing.JLabel jenisPaketLabel;
    private javax.swing.JTextField kdPosReceiveField;
    private javax.swing.JLabel kdPosReceiveLabel;
    private javax.swing.JTextField kdPosSendField;
    private javax.swing.JLabel kdPosSendLabel;
    private javax.swing.JLabel kotaKirimPaketLabel;
    private javax.swing.JComboBox<Object> kotaReceiveCombo;
    private javax.swing.JLabel kotaReceiveLabel;
    private javax.swing.JComboBox<String> kotaSendCombo;
    private javax.swing.JLabel kotaSendLabel;
    private javax.swing.JLabel kotaTujuanPaketLabel;
    private javax.swing.JTextField lPaketField;
    private javax.swing.JComboBox<String> metodeCombo;
    private javax.swing.ButtonGroup metodePGroup;
    private javax.swing.JLabel metodePaketLabel;
    private javax.swing.JTextField namaReceiveField;
    private javax.swing.JLabel namaReceiveLabel;
    private javax.swing.JTextField namaSendField;
    private javax.swing.JLabel namaSendLabel;
    private javax.swing.JRadioButton noAsuransiRadio;
    private javax.swing.JLabel noPaketLabel;
    private javax.swing.JTextField noReceiveField;
    private javax.swing.JLabel noReceiveLabel;
    private javax.swing.JLabel noResiPaketLabel;
    private javax.swing.JTextField noSendField;
    private javax.swing.JLabel noSendLabel;
    private javax.swing.JTextField pPaketField;
    private javax.swing.JTextArea printOutArea;
    private javax.swing.JLabel provinsiReceiveLabel;
    private javax.swing.JTextField provinsiReceiverField;
    private javax.swing.JTextField provinsiSendField;
    private javax.swing.JLabel provinsiSendLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField tPaketField;
    private com.toedter.calendar.JDateChooser tanggalKirimDate;
    private javax.swing.JLabel tanggalPaketLabel;
    private javax.swing.JComboBox<String> tipeCombo;
    private javax.swing.JLabel tipePaketLabel;
    private javax.swing.JLabel tujuanPaketLabel;
    private javax.swing.JRadioButton yesAsuransiRadio;
    // End of variables declaration//GEN-END:variables
}
